### ISSUE TITLE
Add a possibility to pass a and b into NCVis(), instead of min_dist

### ISSUE THREAD

**Issue by dkobak** [stat-ml/ncvis#4]
Would be great if NCVis() allowed to pass a and b values instead of spread and min_dist. UMAP's API does allow it, by the way (if a and b are passed then min_dist and spread are ignored).

This would allow to pass a=b=1 in order to use t-kernel like in t-SNE.

**Comment by alartum** [comment]
Thank you for the proposal, I will add such an option.

**Comment by alartum** [comment]
I have just uploaded the new version to [PyPI](https://pypi.org/project/ncvis/). It will be available in Anaconda by tomorrow, I guess.

**Comment by dkobak** [comment]
Great! Thanks for implementing this so quickly.

**Comment by alartum** [comment]
You're welcome :)
